CREATE TABLE IF NOT EXISTS t_form_template (
    id              VARCHAR(64) PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    source_file     VARCHAR(500),
    source_sha256   VARCHAR(64),
    structure_fingerprint VARCHAR(64),
    analysis_mode   VARCHAR(20),
    schema_json     TEXT NOT NULL,
    ddl_sql         TEXT NOT NULL,
    prototype_html  TEXT,
    stored_source_path VARCHAR(1000),
    error_message   TEXT,
    created_by      VARCHAR(100),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMP,
    status          VARCHAR(20) NOT NULL DEFAULT 'pending_review'
        CHECK (status IN ('processing', 'pending_review', 'active', 'failed', 'inactive')),
    sub_form_count  INTEGER NOT NULL DEFAULT 0,
    storage_table_count INTEGER NOT NULL DEFAULT 0,
    quality_warning TEXT,
    processing_stage VARCHAR(50) NOT NULL DEFAULT 'pending_review',
    processing_duration_seconds INTEGER
);

ALTER TABLE t_form_template ADD COLUMN IF NOT EXISTS storage_table_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE t_form_template ADD COLUMN IF NOT EXISTS quality_warning TEXT;
ALTER TABLE t_form_template ADD COLUMN IF NOT EXISTS processing_stage VARCHAR(50) NOT NULL DEFAULT 'pending_review';
ALTER TABLE t_form_template ADD COLUMN IF NOT EXISTS processing_duration_seconds INTEGER;

CREATE TABLE IF NOT EXISTS t_form_submission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id     VARCHAR(64) NOT NULL,
    template_name   VARCHAR(200),
    form_data_json  TEXT,
    submitted_by    VARCHAR(100),
    submitted_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status          VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'submitted', 'approved', 'rejected')),
    CONSTRAINT fk_submission_template
        FOREIGN KEY (template_id) REFERENCES t_form_template(id)
);
