package com.zhongan.form.util;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

@Component
public class SqlDialectAdapter {

    public List<String> adaptPostgresDdlToH2(String ddl) {
        return splitStatements(ddl).stream().map(this::adaptStatement).toList();
    }

    public List<String> splitStatements(String ddl) {
        String cleaned = ddl.lines()
            .filter(line -> !line.trim().startsWith("--"))
            .collect(Collectors.joining("\n"));

        List<String> statements = new ArrayList<>();
        for (String raw : cleaned.split(";")) {
            String stmt = raw.trim();
            if (!stmt.isEmpty()) {
                statements.add(stmt);
            }
        }
        return statements;
    }

    private String adaptStatement(String statement) {
        String adapted = statement
            .replace("BIGSERIAL", "BIGINT GENERATED BY DEFAULT AS IDENTITY")
            .replace("TIMESTAMPTZ", "TIMESTAMP")
            .replace("JSONB", "CLOB")
            .replace("NOW()", "CURRENT_TIMESTAMP")
            .replace("now()", "CURRENT_TIMESTAMP");

        if (adapted.toLowerCase(Locale.ROOT).startsWith("create index if not exists")) {
            return adapted;
        }
        return adapted;
    }
}
